import { Geist, Geist_Mono } from "next/font/google";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollActions from "./components/ScrollToTop";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${funnelDisplay.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-funnel-display antialiased`}
      >
        <Navbar />
        {children}
        <ScrollActions/>
        <Footer/>
      </body>
    </html>
  );
}
